version: 2

sources:
  - name: Bootcamp_task
    description: healthcare datasets
    database: Bootcamp_task
    schema: public
    tables:
      - name: ICD_Codes
        description: ICD codes for each disease 
        columns:
          - name: Full_Code
            tests:
            - unique
            - not_null
      - name: US_Healthcare_Claims 
        description: Claims data for each member. 
        columns:
          - name: claim_id
            tests:
            - unique
            - not_null
      